export const loginPageActions = {
  LOGIN: 'LOGIN',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR'
};

export const holidayActions = {
  ADD_HOLIDAYS: 'ADD_HOLIDAYS',
  FETCH_HOLIDAYS: 'FETCH_HOLIDAYS',
  DELETE_HOLIDAYS: 'DELETE_HOLIDAYS'
};

const LEAVES = '@leavesView/';
export const leavesActions = {
  ADD_LEAVES: LEAVES + 'ADD_LEAVES',
  FETCH_LEAVES: LEAVES + 'FETCH_LEAVES',
  DELETE_LEAVES: LEAVES + 'DELETE_LEAVES',
  TOGGLE_CALENDAR: LEAVES + 'TOGGLE_CALENDAR',
  UPDATE_STATE: LEAVES + 'UPDATE_STATE'
};
