export const loginPageActions = {
  LOGIN: 'LOGIN',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR'
};

export const holidayActions = {
  ADD_HOLIDAYS: 'ADD_HOLIDAYS',
  FETCH_HOLIDAYS: 'FETCH_HOLIDAYS',
  DELETE_HOLIDAYS: 'DELETE_HOLIDAYS'
};

export const leavesActions = {
  ADD_LEAVES: 'ADD_LEAVES',
  FETCH_LEAVES: 'FETCH_LEAVES',
  DELETE_LEAVES: 'DELETE_LEAVES',
  TOGGLE_CALENDAR: 'TOGGLE_CALENDAR'
};
